[package]
name = "sequential"
version = "0.1.0"
edition = "2021"

[lib]
name = "sequential"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3-ffi = { path = "../../pyo3-ffi", features = ["extension-module"] }

[workspace]
