name: benches

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}-benches
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            pyo3-benches
        continue-on-error: true

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed

      - name: Install nox
        run: pip install nox

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: nox -s codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
