name: benches

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            pyo3-benches/target
            target
          key: cargo-${{ runner.os }}-bench-${{ hashFiles('**/Cargo.toml') }}
        continue-on-error: true

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed

      - name: Install nox
        run: pip install nox

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: nox -s codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
